// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: agent_framework.proto

package agent_framework

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_agent_framework_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_agent_framework_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_agent_framework_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_agent_framework_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_agent_framework_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_agent_framework_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_agent_framework_proto protoreflect.FileDescriptor

const file_agent_framework_proto_rawDesc = "" +
	"\n" +
	"\x15agent_framework.proto\x12\x0fagent_framework\"\x1f\n" +
	"\aRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"\x1c\n" +
	"\bResponse\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg2G\n" +
	"\aService\x12<\n" +
	"\x05Hello\x12\x18.agent_framework.Request\x1a\x19.agent_framework.ResponseB%Z#github.com/xtclirui/agent_frameworkb\x06proto3"

var (
	file_agent_framework_proto_rawDescOnce sync.Once
	file_agent_framework_proto_rawDescData []byte
)

func file_agent_framework_proto_rawDescGZIP() []byte {
	file_agent_framework_proto_rawDescOnce.Do(func() {
		file_agent_framework_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_framework_proto_rawDesc), len(file_agent_framework_proto_rawDesc)))
	})
	return file_agent_framework_proto_rawDescData
}

var file_agent_framework_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_agent_framework_proto_goTypes = []any{
	(*Request)(nil),  // 0: agent_framework.Request
	(*Response)(nil), // 1: agent_framework.Response
}
var file_agent_framework_proto_depIdxs = []int32{
	0, // 0: agent_framework.Service.Hello:input_type -> agent_framework.Request
	1, // 1: agent_framework.Service.Hello:output_type -> agent_framework.Response
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_agent_framework_proto_init() }
func file_agent_framework_proto_init() {
	if File_agent_framework_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_framework_proto_rawDesc), len(file_agent_framework_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_framework_proto_goTypes,
		DependencyIndexes: file_agent_framework_proto_depIdxs,
		MessageInfos:      file_agent_framework_proto_msgTypes,
	}.Build()
	File_agent_framework_proto = out.File
	file_agent_framework_proto_goTypes = nil
	file_agent_framework_proto_depIdxs = nil
}
