// Code generated by trpc-go/trpc-cmdline v1.0.9. DO NOT EDIT.
// source: agent_framework.proto

package agent_framework

import (
	"context"
	"errors"
	"fmt"

	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// IntentService defines service.
type IntentService interface {
	Recognize(ctx context.Context, req *Request) (*Response, error)
}

func IntentService_Recognize_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &Request{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(IntentService).Recognize(ctx, reqbody.(*Request))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// IntentServer_ServiceDesc descriptor for server.RegisterService.
var IntentServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "agent_framework.Intent",
	HandlerType: ((*IntentService)(nil)),
	Methods: []server.Method{
		{
			Name: "/agent_framework.Intent/recognize",
			Func: IntentService_Recognize_Handler,
		},
	},
}

// RegisterIntentService registers service.
func RegisterIntentService(s server.Service, svr IntentService) {
	if err := s.Register(&IntentServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("Intent register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedIntent struct{}

func (s *UnimplementedIntent) Recognize(ctx context.Context, req *Request) (*Response, error) {
	return nil, errors.New("rpc Recognize of service Intent is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// IntentClientProxy defines service client proxy
type IntentClientProxy interface {
	Recognize(ctx context.Context, req *Request, opts ...client.Option) (rsp *Response, err error)
}

type IntentClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewIntentClientProxy = func(opts ...client.Option) IntentClientProxy {
	return &IntentClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *IntentClientProxyImpl) Recognize(ctx context.Context, req *Request, opts ...client.Option) (*Response, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/agent_framework.Intent/recognize")
	msg.WithCalleeServiceName(IntentServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("Intent")
	msg.WithCalleeMethod("Recognize")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &Response{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
