// Code generated by MockGen. DO NOT EDIT.
// Source: agent_framework.trpc.go
//
// Generated by this command:
//
//	mockgen -destination=agent_framework_mock.go -package=agent_framework --source=agent_framework.trpc.go -self_package=github.com/xtclirui/agent_framework
//

// Package agent_framework is a generated GoMock package.
package agent_framework

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	client "trpc.group/trpc-go/trpc-go/client"
)

// MockIntentService is a mock of IntentService interface.
type MockIntentService struct {
	ctrl     *gomock.Controller
	recorder *MockIntentServiceMockRecorder
}

// MockIntentServiceMockRecorder is the mock recorder for MockIntentService.
type MockIntentServiceMockRecorder struct {
	mock *MockIntentService
}

// NewMockIntentService creates a new mock instance.
func NewMockIntentService(ctrl *gomock.Controller) *MockIntentService {
	mock := &MockIntentService{ctrl: ctrl}
	mock.recorder = &MockIntentServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIntentService) EXPECT() *MockIntentServiceMockRecorder {
	return m.recorder
}

// ISGOMOCK indicates that this struct is a gomock mock.
func (m *MockIntentService) ISGOMOCK() struct{} {
	return struct{}{}
}

// Recognize mocks base method.
func (m *MockIntentService) Recognize(ctx context.Context, req *Request) (*Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recognize", ctx, req)
	ret0, _ := ret[0].(*Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recognize indicates an expected call of Recognize.
func (mr *MockIntentServiceMockRecorder) Recognize(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recognize", reflect.TypeOf((*MockIntentService)(nil).Recognize), ctx, req)
}

// MockIntentClientProxy is a mock of IntentClientProxy interface.
type MockIntentClientProxy struct {
	ctrl     *gomock.Controller
	recorder *MockIntentClientProxyMockRecorder
}

// MockIntentClientProxyMockRecorder is the mock recorder for MockIntentClientProxy.
type MockIntentClientProxyMockRecorder struct {
	mock *MockIntentClientProxy
}

// NewMockIntentClientProxy creates a new mock instance.
func NewMockIntentClientProxy(ctrl *gomock.Controller) *MockIntentClientProxy {
	mock := &MockIntentClientProxy{ctrl: ctrl}
	mock.recorder = &MockIntentClientProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIntentClientProxy) EXPECT() *MockIntentClientProxyMockRecorder {
	return m.recorder
}

// ISGOMOCK indicates that this struct is a gomock mock.
func (m *MockIntentClientProxy) ISGOMOCK() struct{} {
	return struct{}{}
}

// Recognize mocks base method.
func (m *MockIntentClientProxy) Recognize(ctx context.Context, req *Request, opts ...client.Option) (*Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Recognize", varargs...)
	ret0, _ := ret[0].(*Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recognize indicates an expected call of Recognize.
func (mr *MockIntentClientProxyMockRecorder) Recognize(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recognize", reflect.TypeOf((*MockIntentClientProxy)(nil).Recognize), varargs...)
}
