// Code generated by trpc-go/trpc-cmdline v1.0.9. DO NOT EDIT.
// source: agent_framework.proto

package agent_framework

import (
	"context"
	"errors"
	"fmt"

	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// ServiceService defines service.
type ServiceService interface {
	Hello(ctx context.Context, req *Request) (*Response, error)
}

func ServiceService_Hello_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &Request{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(ServiceService).Hello(ctx, reqbody.(*Request))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// ServiceServer_ServiceDesc descriptor for server.RegisterService.
var ServiceServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "agent_framework.Service",
	HandlerType: ((*ServiceService)(nil)),
	Methods: []server.Method{
		{
			Name: "/agent_framework.Service/Hello",
			Func: ServiceService_Hello_Handler,
		},
	},
}

// RegisterServiceService registers service.
func RegisterServiceService(s server.Service, svr ServiceService) {
	if err := s.Register(&ServiceServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("Service register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedService struct{}

func (s *UnimplementedService) Hello(ctx context.Context, req *Request) (*Response, error) {
	return nil, errors.New("rpc Hello of service Service is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// ServiceClientProxy defines service client proxy
type ServiceClientProxy interface {
	Hello(ctx context.Context, req *Request, opts ...client.Option) (rsp *Response, err error)
}

type ServiceClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewServiceClientProxy = func(opts ...client.Option) ServiceClientProxy {
	return &ServiceClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *ServiceClientProxyImpl) Hello(ctx context.Context, req *Request, opts ...client.Option) (*Response, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/agent_framework.Service/Hello")
	msg.WithCalleeServiceName(ServiceServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("Service")
	msg.WithCalleeMethod("Hello")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &Response{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
