// Code generated by MockGen. DO NOT EDIT.
// Source: agent_framework.trpc.go
//
// Generated by this command:
//
//	mockgen -destination=agent_framework_mock.go -package=agent_framework --source=agent_framework.trpc.go -self_package=github.com/xtclirui/agent_framework
//

// Package agent_framework is a generated GoMock package.
package agent_framework

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	client "trpc.group/trpc-go/trpc-go/client"
)

// MockServiceService is a mock of ServiceService interface.
type MockServiceService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceServiceMockRecorder
}

// MockServiceServiceMockRecorder is the mock recorder for MockServiceService.
type MockServiceServiceMockRecorder struct {
	mock *MockServiceService
}

// NewMockServiceService creates a new mock instance.
func NewMockServiceService(ctrl *gomock.Controller) *MockServiceService {
	mock := &MockServiceService{ctrl: ctrl}
	mock.recorder = &MockServiceServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceService) EXPECT() *MockServiceServiceMockRecorder {
	return m.recorder
}

// ISGOMOCK indicates that this struct is a gomock mock.
func (m *MockServiceService) ISGOMOCK() struct{} {
	return struct{}{}
}

// Hello mocks base method.
func (m *MockServiceService) Hello(ctx context.Context, req *Request) (*Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hello", ctx, req)
	ret0, _ := ret[0].(*Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Hello indicates an expected call of Hello.
func (mr *MockServiceServiceMockRecorder) Hello(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hello", reflect.TypeOf((*MockServiceService)(nil).Hello), ctx, req)
}

// MockServiceClientProxy is a mock of ServiceClientProxy interface.
type MockServiceClientProxy struct {
	ctrl     *gomock.Controller
	recorder *MockServiceClientProxyMockRecorder
}

// MockServiceClientProxyMockRecorder is the mock recorder for MockServiceClientProxy.
type MockServiceClientProxyMockRecorder struct {
	mock *MockServiceClientProxy
}

// NewMockServiceClientProxy creates a new mock instance.
func NewMockServiceClientProxy(ctrl *gomock.Controller) *MockServiceClientProxy {
	mock := &MockServiceClientProxy{ctrl: ctrl}
	mock.recorder = &MockServiceClientProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceClientProxy) EXPECT() *MockServiceClientProxyMockRecorder {
	return m.recorder
}

// ISGOMOCK indicates that this struct is a gomock mock.
func (m *MockServiceClientProxy) ISGOMOCK() struct{} {
	return struct{}{}
}

// Hello mocks base method.
func (m *MockServiceClientProxy) Hello(ctx context.Context, req *Request, opts ...client.Option) (*Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Hello", varargs...)
	ret0, _ := ret[0].(*Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Hello indicates an expected call of Hello.
func (mr *MockServiceClientProxyMockRecorder) Hello(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hello", reflect.TypeOf((*MockServiceClientProxy)(nil).Hello), varargs...)
}
